#ifndef __main__
#define __main__

// main wxWidgets header file
#include <wx/wx.h>
// gui classes generated by wxFormBuilder
#include "gui.h"
#include "gameElements.h"


////////////////////////////////////////////////////////////////////////////////
// application class declaration 
////////////////////////////////////////////////////////////////////////////////

class MainApp : public wxApp
{
	public:
		virtual bool OnInit();
};

// declare global static function wxGetApp()
DECLARE_APP(MainApp)

////////////////////////////////////////////////////////////////////////////////
// main application frame declaration 
////////////////////////////////////////////////////////////////////////////////

class Game : public wxTimer
{
public:
	Game( wxFrame *window);
	virtual ~Game();
	
	void Draw(wxDC& dc);
	void SetMouseMove(wxPoint pos);
	void StartTimer();
	void StopTimer();
	
protected:
	wxFrame *m_ParentFrame;
	Bat *m_AiBat;
	Bat *m_PlayerBat;
	Ball *m_Ball;
	wxPoint ballPos;
	int x, y, kx, ky;
	wxPoint mousePos;
	wxCoord mousePosYOld;
		
	
	virtual void Notify();
	
};

class MainFrame : public MainFrameBase
{
	public:
		MainFrame( wxWindow *parent );
		virtual ~MainFrame();
		
	protected:
		Game *m_Game;
		bool timerRunning;
		// protected event handlers
		virtual void OnCloseFrame( wxCloseEvent& event );
		virtual void OnExitClick( wxCommandEvent& event );
		virtual void OnEraseBackground(wxEraseEvent& event);
		virtual void OnPaint(wxPaintEvent& event);
		virtual void OnMouseMove(wxMouseEvent& event);
};



#endif //__main__

